// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jwumq_external_message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_jwumq_5fexternal_5fmessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_jwumq_5fexternal_5fmessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_jwumq_5fexternal_5fmessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_jwumq_5fexternal_5fmessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_jwumq_5fexternal_5fmessage_2eproto;
namespace jwumq_external_message_pb {
class jwumq_external_message;
class jwumq_external_messageDefaultTypeInternal;
extern jwumq_external_messageDefaultTypeInternal _jwumq_external_message_default_instance_;
}  // namespace jwumq_external_message_pb
PROTOBUF_NAMESPACE_OPEN
template<> ::jwumq_external_message_pb::jwumq_external_message* Arena::CreateMaybeMessage<::jwumq_external_message_pb::jwumq_external_message>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace jwumq_external_message_pb {

// ===================================================================

class jwumq_external_message :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:jwumq_external_message_pb.jwumq_external_message) */ {
 public:
  jwumq_external_message();
  virtual ~jwumq_external_message();

  jwumq_external_message(const jwumq_external_message& from);
  jwumq_external_message(jwumq_external_message&& from) noexcept
    : jwumq_external_message() {
    *this = ::std::move(from);
  }

  inline jwumq_external_message& operator=(const jwumq_external_message& from) {
    CopyFrom(from);
    return *this;
  }
  inline jwumq_external_message& operator=(jwumq_external_message&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const jwumq_external_message& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const jwumq_external_message* internal_default_instance() {
    return reinterpret_cast<const jwumq_external_message*>(
               &_jwumq_external_message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(jwumq_external_message& a, jwumq_external_message& b) {
    a.Swap(&b);
  }
  inline void Swap(jwumq_external_message* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline jwumq_external_message* New() const final {
    return CreateMaybeMessage<jwumq_external_message>(nullptr);
  }

  jwumq_external_message* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<jwumq_external_message>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const jwumq_external_message& from);
  void MergeFrom(const jwumq_external_message& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(jwumq_external_message* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "jwumq_external_message_pb.jwumq_external_message";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_jwumq_5fexternal_5fmessage_2eproto);
    return ::descriptor_table_jwumq_5fexternal_5fmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSrcIdFieldNumber = 5,
    kDesIdFieldNumber = 6,
    kQueueNameFieldNumber = 7,
    kRawDataFieldNumber = 9,
    kCommandFieldNumber = 1,
    kTsSecFieldNumber = 2,
    kTsUsFieldNumber = 3,
    kSnFieldNumber = 4,
    kRawDataLenFieldNumber = 8,
  };
  // string src_id = 5;
  void clear_src_id();
  const std::string& src_id() const;
  void set_src_id(const std::string& value);
  void set_src_id(std::string&& value);
  void set_src_id(const char* value);
  void set_src_id(const char* value, size_t size);
  std::string* mutable_src_id();
  std::string* release_src_id();
  void set_allocated_src_id(std::string* src_id);
  private:
  const std::string& _internal_src_id() const;
  void _internal_set_src_id(const std::string& value);
  std::string* _internal_mutable_src_id();
  public:

  // string des_id = 6;
  void clear_des_id();
  const std::string& des_id() const;
  void set_des_id(const std::string& value);
  void set_des_id(std::string&& value);
  void set_des_id(const char* value);
  void set_des_id(const char* value, size_t size);
  std::string* mutable_des_id();
  std::string* release_des_id();
  void set_allocated_des_id(std::string* des_id);
  private:
  const std::string& _internal_des_id() const;
  void _internal_set_des_id(const std::string& value);
  std::string* _internal_mutable_des_id();
  public:

  // string queue_name = 7;
  void clear_queue_name();
  const std::string& queue_name() const;
  void set_queue_name(const std::string& value);
  void set_queue_name(std::string&& value);
  void set_queue_name(const char* value);
  void set_queue_name(const char* value, size_t size);
  std::string* mutable_queue_name();
  std::string* release_queue_name();
  void set_allocated_queue_name(std::string* queue_name);
  private:
  const std::string& _internal_queue_name() const;
  void _internal_set_queue_name(const std::string& value);
  std::string* _internal_mutable_queue_name();
  public:

  // bytes raw_data = 9;
  void clear_raw_data();
  const std::string& raw_data() const;
  void set_raw_data(const std::string& value);
  void set_raw_data(std::string&& value);
  void set_raw_data(const char* value);
  void set_raw_data(const void* value, size_t size);
  std::string* mutable_raw_data();
  std::string* release_raw_data();
  void set_allocated_raw_data(std::string* raw_data);
  private:
  const std::string& _internal_raw_data() const;
  void _internal_set_raw_data(const std::string& value);
  std::string* _internal_mutable_raw_data();
  public:

  // uint32 command = 1;
  void clear_command();
  ::PROTOBUF_NAMESPACE_ID::uint32 command() const;
  void set_command(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_command() const;
  void _internal_set_command(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 ts_sec = 2;
  void clear_ts_sec();
  ::PROTOBUF_NAMESPACE_ID::uint32 ts_sec() const;
  void set_ts_sec(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_ts_sec() const;
  void _internal_set_ts_sec(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 ts_us = 3;
  void clear_ts_us();
  ::PROTOBUF_NAMESPACE_ID::uint32 ts_us() const;
  void set_ts_us(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_ts_us() const;
  void _internal_set_ts_us(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 sn = 4;
  void clear_sn();
  ::PROTOBUF_NAMESPACE_ID::uint32 sn() const;
  void set_sn(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_sn() const;
  void _internal_set_sn(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 raw_data_len = 8;
  void clear_raw_data_len();
  ::PROTOBUF_NAMESPACE_ID::uint32 raw_data_len() const;
  void set_raw_data_len(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_raw_data_len() const;
  void _internal_set_raw_data_len(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:jwumq_external_message_pb.jwumq_external_message)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr src_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr des_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr queue_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr raw_data_;
  ::PROTOBUF_NAMESPACE_ID::uint32 command_;
  ::PROTOBUF_NAMESPACE_ID::uint32 ts_sec_;
  ::PROTOBUF_NAMESPACE_ID::uint32 ts_us_;
  ::PROTOBUF_NAMESPACE_ID::uint32 sn_;
  ::PROTOBUF_NAMESPACE_ID::uint32 raw_data_len_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_jwumq_5fexternal_5fmessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// jwumq_external_message

// uint32 command = 1;
inline void jwumq_external_message::clear_command() {
  command_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 jwumq_external_message::_internal_command() const {
  return command_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 jwumq_external_message::command() const {
  // @@protoc_insertion_point(field_get:jwumq_external_message_pb.jwumq_external_message.command)
  return _internal_command();
}
inline void jwumq_external_message::_internal_set_command(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  command_ = value;
}
inline void jwumq_external_message::set_command(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_command(value);
  // @@protoc_insertion_point(field_set:jwumq_external_message_pb.jwumq_external_message.command)
}

// uint32 ts_sec = 2;
inline void jwumq_external_message::clear_ts_sec() {
  ts_sec_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 jwumq_external_message::_internal_ts_sec() const {
  return ts_sec_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 jwumq_external_message::ts_sec() const {
  // @@protoc_insertion_point(field_get:jwumq_external_message_pb.jwumq_external_message.ts_sec)
  return _internal_ts_sec();
}
inline void jwumq_external_message::_internal_set_ts_sec(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  ts_sec_ = value;
}
inline void jwumq_external_message::set_ts_sec(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_ts_sec(value);
  // @@protoc_insertion_point(field_set:jwumq_external_message_pb.jwumq_external_message.ts_sec)
}

// uint32 ts_us = 3;
inline void jwumq_external_message::clear_ts_us() {
  ts_us_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 jwumq_external_message::_internal_ts_us() const {
  return ts_us_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 jwumq_external_message::ts_us() const {
  // @@protoc_insertion_point(field_get:jwumq_external_message_pb.jwumq_external_message.ts_us)
  return _internal_ts_us();
}
inline void jwumq_external_message::_internal_set_ts_us(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  ts_us_ = value;
}
inline void jwumq_external_message::set_ts_us(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_ts_us(value);
  // @@protoc_insertion_point(field_set:jwumq_external_message_pb.jwumq_external_message.ts_us)
}

// uint32 sn = 4;
inline void jwumq_external_message::clear_sn() {
  sn_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 jwumq_external_message::_internal_sn() const {
  return sn_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 jwumq_external_message::sn() const {
  // @@protoc_insertion_point(field_get:jwumq_external_message_pb.jwumq_external_message.sn)
  return _internal_sn();
}
inline void jwumq_external_message::_internal_set_sn(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  sn_ = value;
}
inline void jwumq_external_message::set_sn(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_sn(value);
  // @@protoc_insertion_point(field_set:jwumq_external_message_pb.jwumq_external_message.sn)
}

// string src_id = 5;
inline void jwumq_external_message::clear_src_id() {
  src_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& jwumq_external_message::src_id() const {
  // @@protoc_insertion_point(field_get:jwumq_external_message_pb.jwumq_external_message.src_id)
  return _internal_src_id();
}
inline void jwumq_external_message::set_src_id(const std::string& value) {
  _internal_set_src_id(value);
  // @@protoc_insertion_point(field_set:jwumq_external_message_pb.jwumq_external_message.src_id)
}
inline std::string* jwumq_external_message::mutable_src_id() {
  // @@protoc_insertion_point(field_mutable:jwumq_external_message_pb.jwumq_external_message.src_id)
  return _internal_mutable_src_id();
}
inline const std::string& jwumq_external_message::_internal_src_id() const {
  return src_id_.GetNoArena();
}
inline void jwumq_external_message::_internal_set_src_id(const std::string& value) {
  
  src_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void jwumq_external_message::set_src_id(std::string&& value) {
  
  src_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:jwumq_external_message_pb.jwumq_external_message.src_id)
}
inline void jwumq_external_message::set_src_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  src_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:jwumq_external_message_pb.jwumq_external_message.src_id)
}
inline void jwumq_external_message::set_src_id(const char* value, size_t size) {
  
  src_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:jwumq_external_message_pb.jwumq_external_message.src_id)
}
inline std::string* jwumq_external_message::_internal_mutable_src_id() {
  
  return src_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* jwumq_external_message::release_src_id() {
  // @@protoc_insertion_point(field_release:jwumq_external_message_pb.jwumq_external_message.src_id)
  
  return src_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void jwumq_external_message::set_allocated_src_id(std::string* src_id) {
  if (src_id != nullptr) {
    
  } else {
    
  }
  src_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), src_id);
  // @@protoc_insertion_point(field_set_allocated:jwumq_external_message_pb.jwumq_external_message.src_id)
}

// string des_id = 6;
inline void jwumq_external_message::clear_des_id() {
  des_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& jwumq_external_message::des_id() const {
  // @@protoc_insertion_point(field_get:jwumq_external_message_pb.jwumq_external_message.des_id)
  return _internal_des_id();
}
inline void jwumq_external_message::set_des_id(const std::string& value) {
  _internal_set_des_id(value);
  // @@protoc_insertion_point(field_set:jwumq_external_message_pb.jwumq_external_message.des_id)
}
inline std::string* jwumq_external_message::mutable_des_id() {
  // @@protoc_insertion_point(field_mutable:jwumq_external_message_pb.jwumq_external_message.des_id)
  return _internal_mutable_des_id();
}
inline const std::string& jwumq_external_message::_internal_des_id() const {
  return des_id_.GetNoArena();
}
inline void jwumq_external_message::_internal_set_des_id(const std::string& value) {
  
  des_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void jwumq_external_message::set_des_id(std::string&& value) {
  
  des_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:jwumq_external_message_pb.jwumq_external_message.des_id)
}
inline void jwumq_external_message::set_des_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  des_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:jwumq_external_message_pb.jwumq_external_message.des_id)
}
inline void jwumq_external_message::set_des_id(const char* value, size_t size) {
  
  des_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:jwumq_external_message_pb.jwumq_external_message.des_id)
}
inline std::string* jwumq_external_message::_internal_mutable_des_id() {
  
  return des_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* jwumq_external_message::release_des_id() {
  // @@protoc_insertion_point(field_release:jwumq_external_message_pb.jwumq_external_message.des_id)
  
  return des_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void jwumq_external_message::set_allocated_des_id(std::string* des_id) {
  if (des_id != nullptr) {
    
  } else {
    
  }
  des_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), des_id);
  // @@protoc_insertion_point(field_set_allocated:jwumq_external_message_pb.jwumq_external_message.des_id)
}

// string queue_name = 7;
inline void jwumq_external_message::clear_queue_name() {
  queue_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& jwumq_external_message::queue_name() const {
  // @@protoc_insertion_point(field_get:jwumq_external_message_pb.jwumq_external_message.queue_name)
  return _internal_queue_name();
}
inline void jwumq_external_message::set_queue_name(const std::string& value) {
  _internal_set_queue_name(value);
  // @@protoc_insertion_point(field_set:jwumq_external_message_pb.jwumq_external_message.queue_name)
}
inline std::string* jwumq_external_message::mutable_queue_name() {
  // @@protoc_insertion_point(field_mutable:jwumq_external_message_pb.jwumq_external_message.queue_name)
  return _internal_mutable_queue_name();
}
inline const std::string& jwumq_external_message::_internal_queue_name() const {
  return queue_name_.GetNoArena();
}
inline void jwumq_external_message::_internal_set_queue_name(const std::string& value) {
  
  queue_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void jwumq_external_message::set_queue_name(std::string&& value) {
  
  queue_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:jwumq_external_message_pb.jwumq_external_message.queue_name)
}
inline void jwumq_external_message::set_queue_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  queue_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:jwumq_external_message_pb.jwumq_external_message.queue_name)
}
inline void jwumq_external_message::set_queue_name(const char* value, size_t size) {
  
  queue_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:jwumq_external_message_pb.jwumq_external_message.queue_name)
}
inline std::string* jwumq_external_message::_internal_mutable_queue_name() {
  
  return queue_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* jwumq_external_message::release_queue_name() {
  // @@protoc_insertion_point(field_release:jwumq_external_message_pb.jwumq_external_message.queue_name)
  
  return queue_name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void jwumq_external_message::set_allocated_queue_name(std::string* queue_name) {
  if (queue_name != nullptr) {
    
  } else {
    
  }
  queue_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), queue_name);
  // @@protoc_insertion_point(field_set_allocated:jwumq_external_message_pb.jwumq_external_message.queue_name)
}

// uint32 raw_data_len = 8;
inline void jwumq_external_message::clear_raw_data_len() {
  raw_data_len_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 jwumq_external_message::_internal_raw_data_len() const {
  return raw_data_len_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 jwumq_external_message::raw_data_len() const {
  // @@protoc_insertion_point(field_get:jwumq_external_message_pb.jwumq_external_message.raw_data_len)
  return _internal_raw_data_len();
}
inline void jwumq_external_message::_internal_set_raw_data_len(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  raw_data_len_ = value;
}
inline void jwumq_external_message::set_raw_data_len(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_raw_data_len(value);
  // @@protoc_insertion_point(field_set:jwumq_external_message_pb.jwumq_external_message.raw_data_len)
}

// bytes raw_data = 9;
inline void jwumq_external_message::clear_raw_data() {
  raw_data_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& jwumq_external_message::raw_data() const {
  // @@protoc_insertion_point(field_get:jwumq_external_message_pb.jwumq_external_message.raw_data)
  return _internal_raw_data();
}
inline void jwumq_external_message::set_raw_data(const std::string& value) {
  _internal_set_raw_data(value);
  // @@protoc_insertion_point(field_set:jwumq_external_message_pb.jwumq_external_message.raw_data)
}
inline std::string* jwumq_external_message::mutable_raw_data() {
  // @@protoc_insertion_point(field_mutable:jwumq_external_message_pb.jwumq_external_message.raw_data)
  return _internal_mutable_raw_data();
}
inline const std::string& jwumq_external_message::_internal_raw_data() const {
  return raw_data_.GetNoArena();
}
inline void jwumq_external_message::_internal_set_raw_data(const std::string& value) {
  
  raw_data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void jwumq_external_message::set_raw_data(std::string&& value) {
  
  raw_data_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:jwumq_external_message_pb.jwumq_external_message.raw_data)
}
inline void jwumq_external_message::set_raw_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  raw_data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:jwumq_external_message_pb.jwumq_external_message.raw_data)
}
inline void jwumq_external_message::set_raw_data(const void* value, size_t size) {
  
  raw_data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:jwumq_external_message_pb.jwumq_external_message.raw_data)
}
inline std::string* jwumq_external_message::_internal_mutable_raw_data() {
  
  return raw_data_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* jwumq_external_message::release_raw_data() {
  // @@protoc_insertion_point(field_release:jwumq_external_message_pb.jwumq_external_message.raw_data)
  
  return raw_data_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void jwumq_external_message::set_allocated_raw_data(std::string* raw_data) {
  if (raw_data != nullptr) {
    
  } else {
    
  }
  raw_data_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), raw_data);
  // @@protoc_insertion_point(field_set_allocated:jwumq_external_message_pb.jwumq_external_message.raw_data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace jwumq_external_message_pb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_jwumq_5fexternal_5fmessage_2eproto
