// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jwumq_external_message.proto

#include "jwumq_external_message.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace jwumq_external_message_pb {
class jwumq_external_messageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<jwumq_external_message> _instance;
} _jwumq_external_message_default_instance_;
}  // namespace jwumq_external_message_pb
static void InitDefaultsscc_info_jwumq_external_message_jwumq_5fexternal_5fmessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::jwumq_external_message_pb::_jwumq_external_message_default_instance_;
    new (ptr) ::jwumq_external_message_pb::jwumq_external_message();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::jwumq_external_message_pb::jwumq_external_message::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_jwumq_external_message_jwumq_5fexternal_5fmessage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_jwumq_external_message_jwumq_5fexternal_5fmessage_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_jwumq_5fexternal_5fmessage_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_jwumq_5fexternal_5fmessage_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_jwumq_5fexternal_5fmessage_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_jwumq_5fexternal_5fmessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::jwumq_external_message_pb::jwumq_external_message, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::jwumq_external_message_pb::jwumq_external_message, command_),
  PROTOBUF_FIELD_OFFSET(::jwumq_external_message_pb::jwumq_external_message, ts_sec_),
  PROTOBUF_FIELD_OFFSET(::jwumq_external_message_pb::jwumq_external_message, ts_us_),
  PROTOBUF_FIELD_OFFSET(::jwumq_external_message_pb::jwumq_external_message, sn_),
  PROTOBUF_FIELD_OFFSET(::jwumq_external_message_pb::jwumq_external_message, src_id_),
  PROTOBUF_FIELD_OFFSET(::jwumq_external_message_pb::jwumq_external_message, des_id_),
  PROTOBUF_FIELD_OFFSET(::jwumq_external_message_pb::jwumq_external_message, queue_name_),
  PROTOBUF_FIELD_OFFSET(::jwumq_external_message_pb::jwumq_external_message, raw_data_len_),
  PROTOBUF_FIELD_OFFSET(::jwumq_external_message_pb::jwumq_external_message, raw_data_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::jwumq_external_message_pb::jwumq_external_message)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::jwumq_external_message_pb::_jwumq_external_message_default_instance_),
};

const char descriptor_table_protodef_jwumq_5fexternal_5fmessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\034jwumq_external_message.proto\022\031jwumq_ex"
  "ternal_message_pb\"\260\001\n\026jwumq_external_mes"
  "sage\022\017\n\007command\030\001 \001(\r\022\016\n\006ts_sec\030\002 \001(\r\022\r\n"
  "\005ts_us\030\003 \001(\r\022\n\n\002sn\030\004 \001(\r\022\016\n\006src_id\030\005 \001(\t"
  "\022\016\n\006des_id\030\006 \001(\t\022\022\n\nqueue_name\030\007 \001(\t\022\024\n\014"
  "raw_data_len\030\010 \001(\r\022\020\n\010raw_data\030\t \001(\014b\006pr"
  "oto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_jwumq_5fexternal_5fmessage_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_jwumq_5fexternal_5fmessage_2eproto_sccs[1] = {
  &scc_info_jwumq_external_message_jwumq_5fexternal_5fmessage_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_jwumq_5fexternal_5fmessage_2eproto_once;
static bool descriptor_table_jwumq_5fexternal_5fmessage_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_jwumq_5fexternal_5fmessage_2eproto = {
  &descriptor_table_jwumq_5fexternal_5fmessage_2eproto_initialized, descriptor_table_protodef_jwumq_5fexternal_5fmessage_2eproto, "jwumq_external_message.proto", 244,
  &descriptor_table_jwumq_5fexternal_5fmessage_2eproto_once, descriptor_table_jwumq_5fexternal_5fmessage_2eproto_sccs, descriptor_table_jwumq_5fexternal_5fmessage_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_jwumq_5fexternal_5fmessage_2eproto::offsets,
  file_level_metadata_jwumq_5fexternal_5fmessage_2eproto, 1, file_level_enum_descriptors_jwumq_5fexternal_5fmessage_2eproto, file_level_service_descriptors_jwumq_5fexternal_5fmessage_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_jwumq_5fexternal_5fmessage_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_jwumq_5fexternal_5fmessage_2eproto), true);
namespace jwumq_external_message_pb {

// ===================================================================

void jwumq_external_message::InitAsDefaultInstance() {
}
class jwumq_external_message::_Internal {
 public:
};

jwumq_external_message::jwumq_external_message()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:jwumq_external_message_pb.jwumq_external_message)
}
jwumq_external_message::jwumq_external_message(const jwumq_external_message& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  src_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_src_id().empty()) {
    src_id_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.src_id_);
  }
  des_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_des_id().empty()) {
    des_id_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.des_id_);
  }
  queue_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_queue_name().empty()) {
    queue_name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.queue_name_);
  }
  raw_data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_raw_data().empty()) {
    raw_data_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.raw_data_);
  }
  ::memcpy(&command_, &from.command_,
    static_cast<size_t>(reinterpret_cast<char*>(&raw_data_len_) -
    reinterpret_cast<char*>(&command_)) + sizeof(raw_data_len_));
  // @@protoc_insertion_point(copy_constructor:jwumq_external_message_pb.jwumq_external_message)
}

void jwumq_external_message::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_jwumq_external_message_jwumq_5fexternal_5fmessage_2eproto.base);
  src_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  des_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  queue_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  raw_data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&command_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&raw_data_len_) -
      reinterpret_cast<char*>(&command_)) + sizeof(raw_data_len_));
}

jwumq_external_message::~jwumq_external_message() {
  // @@protoc_insertion_point(destructor:jwumq_external_message_pb.jwumq_external_message)
  SharedDtor();
}

void jwumq_external_message::SharedDtor() {
  src_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  des_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  queue_name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  raw_data_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void jwumq_external_message::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const jwumq_external_message& jwumq_external_message::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_jwumq_external_message_jwumq_5fexternal_5fmessage_2eproto.base);
  return *internal_default_instance();
}


void jwumq_external_message::Clear() {
// @@protoc_insertion_point(message_clear_start:jwumq_external_message_pb.jwumq_external_message)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  src_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  des_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  queue_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  raw_data_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&command_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&raw_data_len_) -
      reinterpret_cast<char*>(&command_)) + sizeof(raw_data_len_));
  _internal_metadata_.Clear();
}

const char* jwumq_external_message::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 command = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          command_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 ts_sec = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ts_sec_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 ts_us = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ts_us_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 sn = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          sn_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string src_id = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_src_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "jwumq_external_message_pb.jwumq_external_message.src_id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string des_id = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_des_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "jwumq_external_message_pb.jwumq_external_message.des_id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string queue_name = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          auto str = _internal_mutable_queue_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "jwumq_external_message_pb.jwumq_external_message.queue_name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 raw_data_len = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          raw_data_len_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes raw_data = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          auto str = _internal_mutable_raw_data();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* jwumq_external_message::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:jwumq_external_message_pb.jwumq_external_message)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 command = 1;
  if (this->command() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_command(), target);
  }

  // uint32 ts_sec = 2;
  if (this->ts_sec() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_ts_sec(), target);
  }

  // uint32 ts_us = 3;
  if (this->ts_us() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_ts_us(), target);
  }

  // uint32 sn = 4;
  if (this->sn() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_sn(), target);
  }

  // string src_id = 5;
  if (this->src_id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_src_id().data(), static_cast<int>(this->_internal_src_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "jwumq_external_message_pb.jwumq_external_message.src_id");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_src_id(), target);
  }

  // string des_id = 6;
  if (this->des_id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_des_id().data(), static_cast<int>(this->_internal_des_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "jwumq_external_message_pb.jwumq_external_message.des_id");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_des_id(), target);
  }

  // string queue_name = 7;
  if (this->queue_name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_queue_name().data(), static_cast<int>(this->_internal_queue_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "jwumq_external_message_pb.jwumq_external_message.queue_name");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_queue_name(), target);
  }

  // uint32 raw_data_len = 8;
  if (this->raw_data_len() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(8, this->_internal_raw_data_len(), target);
  }

  // bytes raw_data = 9;
  if (this->raw_data().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        9, this->_internal_raw_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:jwumq_external_message_pb.jwumq_external_message)
  return target;
}

size_t jwumq_external_message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:jwumq_external_message_pb.jwumq_external_message)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string src_id = 5;
  if (this->src_id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_src_id());
  }

  // string des_id = 6;
  if (this->des_id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_des_id());
  }

  // string queue_name = 7;
  if (this->queue_name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_queue_name());
  }

  // bytes raw_data = 9;
  if (this->raw_data().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_raw_data());
  }

  // uint32 command = 1;
  if (this->command() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_command());
  }

  // uint32 ts_sec = 2;
  if (this->ts_sec() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_ts_sec());
  }

  // uint32 ts_us = 3;
  if (this->ts_us() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_ts_us());
  }

  // uint32 sn = 4;
  if (this->sn() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_sn());
  }

  // uint32 raw_data_len = 8;
  if (this->raw_data_len() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_raw_data_len());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void jwumq_external_message::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:jwumq_external_message_pb.jwumq_external_message)
  GOOGLE_DCHECK_NE(&from, this);
  const jwumq_external_message* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<jwumq_external_message>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:jwumq_external_message_pb.jwumq_external_message)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:jwumq_external_message_pb.jwumq_external_message)
    MergeFrom(*source);
  }
}

void jwumq_external_message::MergeFrom(const jwumq_external_message& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:jwumq_external_message_pb.jwumq_external_message)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.src_id().size() > 0) {

    src_id_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.src_id_);
  }
  if (from.des_id().size() > 0) {

    des_id_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.des_id_);
  }
  if (from.queue_name().size() > 0) {

    queue_name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.queue_name_);
  }
  if (from.raw_data().size() > 0) {

    raw_data_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.raw_data_);
  }
  if (from.command() != 0) {
    _internal_set_command(from._internal_command());
  }
  if (from.ts_sec() != 0) {
    _internal_set_ts_sec(from._internal_ts_sec());
  }
  if (from.ts_us() != 0) {
    _internal_set_ts_us(from._internal_ts_us());
  }
  if (from.sn() != 0) {
    _internal_set_sn(from._internal_sn());
  }
  if (from.raw_data_len() != 0) {
    _internal_set_raw_data_len(from._internal_raw_data_len());
  }
}

void jwumq_external_message::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:jwumq_external_message_pb.jwumq_external_message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void jwumq_external_message::CopyFrom(const jwumq_external_message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:jwumq_external_message_pb.jwumq_external_message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool jwumq_external_message::IsInitialized() const {
  return true;
}

void jwumq_external_message::InternalSwap(jwumq_external_message* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  src_id_.Swap(&other->src_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  des_id_.Swap(&other->des_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  queue_name_.Swap(&other->queue_name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  raw_data_.Swap(&other->raw_data_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(command_, other->command_);
  swap(ts_sec_, other->ts_sec_);
  swap(ts_us_, other->ts_us_);
  swap(sn_, other->sn_);
  swap(raw_data_len_, other->raw_data_len_);
}

::PROTOBUF_NAMESPACE_ID::Metadata jwumq_external_message::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace jwumq_external_message_pb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::jwumq_external_message_pb::jwumq_external_message* Arena::CreateMaybeMessage< ::jwumq_external_message_pb::jwumq_external_message >(Arena* arena) {
  return Arena::CreateInternal< ::jwumq_external_message_pb::jwumq_external_message >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
